### ISSUE TITLE
Set compression for target store

### ISSUE THREAD

**Issue by eric-czech** [pangeo-data/rechunker#46]
Would it make sense for the user to be able to provide the target zarr array instead of just the store?

I'd like to be able to set a compressor for my target, but it appears that there is no way for me to override the arguments given to `zarr.creation.create`.  I.e. I'd like to be able to do this:

```python
from numcodecs import Blosc
import dask.array as da
import zarr

compressor = Blosc(cname='zstd', clevel=1, shuffle=Blosc.BITSHUFFLE)
store = zarr.DirectoryStore('/tmp/ds.zarr/arr')
arr = zarr.create((100, 100), chunks=(10, 10), dtype='float32', store=store, compressor=compressor)
rechunk(
    source=da.random.random((100, 100)),
    target_chunks=(10, 10),
    max_mem='100MB',
    target_store=arr
)
```

Is there some other way to set a compressor right now?

**Comment by TomAugspurger** [comment]
We could easily forward keyword arguments through to the creation.

```
def rechunk(..., intermediate_options=None, target_options=None):
    """
    ...
    intermediate_options, target_options: Dict, optional
        Additional keyword arguments to pass through to the
        creation of the intermediate and target Zarr arrays.

    Examples
    --------
    >>> compressor = Blosc(cname='zstd', clevel=1, shuffle=Blosc.BITSHUFFLE)
    >>> options = dict(compressor=compressor)
    >>> rechunk(..., intermediate_options=options, target_options=options)
```

As for whether the user could provide the array, the main difficulty I see is that they need to get the chunks correct. For the target array, this is fine (they're providing it). It's a bit harder for the intermediate store, since rechunker is computing that based on the max_mem. But perhaps we just validate that they match what we calculate in rechunker and raise if they differ?
