### ISSUE TITLE
conda forge plan?

### ISSUE THREAD

**Issue by phildong** [pangeo-data/rechunker#62]
First of all, I love this package! I found it indispensable in my pipeline that heavily depends on dask and it has become a critical dependency for my project. I'm trying to publish my project to conda-forge, and as far as I understand, I cannot do that with a dependency that's only available through pip. So I'm wondering if there's any plan to bring rechunker to conda-forge? Thank you for the awesome tool!

**Comment by rabernat** [comment]
Hi @phildong! Glad you find rechunker useful.

The only reason we have no conda package is because the devs haven't yet gotten around to this! The project is pretty new and also it's a crazy time for everyone in general right now. It sounds like you're already familiar with conda forge packaging, so we we would be thrilled if you would set up rechunker's conda-forge feedstock. We would do whatever we can to help you out.

**Comment by davidbrochart** [comment]
Done in https://github.com/conda-forge/staged-recipes/pull/13099

**Comment by rabernat** [comment]
This is fantastic @davidbrochart! You are a hero! 🦸

**Comment by davidbrochart** [comment]
Let me know if someone wants to be added as a maintainer of the package in the next release.

**Comment by rabernat** [comment]
Please add me and @TomAugspurger. Thanks!

**Comment by phildong** [comment]
Thiw is awesome! Thank you guys for such terrific (and fast!) work!
